function problems_solved = run_validation_TP_CEA_6
    % Run test validation_TP_CEA_6:
    % Contrasted with: NASA's Chemical Equilibrium with Applications software
    % Problem type: Equilibrium composition at defined T and p
    % Temperature [K]   = 2000:50:5000;
    % Pressure    [bar] = 1.01325;
    % Initial mixture: Si + 9 C6H5OH_phenol
    % List of species considered: LS
    %
    % This example is obtained from [1]
    % 
    % [1] Scoggins, J. B., & Magin, T. E. (2015). Gibbs function continuation
    %     for linearly constrained multiphase equilibria. Combustion and Flame,
    %     162(12), 4514-4522.
    
    % Inputs
    Fuel = {'Si', 'C6H5OH_phenol'};
    moles_Fuel = [1, 9];
    prefixDataName = 'C6H5OH_phenol_and_Si';
    filename = {strcat(prefixDataName, '_TP1.out')};
    LS = {'C','C2','C2H','C10H8_naphthale','C2H2_acetylene',...
    'C2H2_vinylidene','C2H3_vinyl','C2H4','C2H4O_ethylen_o','C2H5',...
    'C2H5OH','C2H6','C2N2','C2O','C3','C3H3_1_propynl',...
    'C3H3_2_propynl','C3H4_allene','C3H4_propyne','C3H5_allyl',...
    'C3H6O_acetone','C3H6_propylene','C3H8','C3O2','C4',...
    'C4H2_butadiyne','C4H6_1butyne','C4H6_2butyne','C4H6_butadiene',...
    'C4H8_1_butene','C4H8_cis2_buten','C4H8_isobutene',...
    'C4H8_tr2_butene','C4H9_i_butyl','C4H9_n_butyl','C4H9_s_butyl',...
    'C4H9_t_butyl','C4N2','C5','C6H2','C6H5OH_phenol','C6H5O_phenoxy',...
    'C6H5_phenyl','C6H6','C7H7_benzyl','C7H8','C8H18_isooctane',...
    'C8H8_styrene','CH','CH2','CH2CO_ketene','CH2OH','CH3',...
    'CH3CHO_ethanal','CH3CN','CH3COOH','CH3CO_acetyl','CH3O',...
    'CH3OCH3','CH3OH','CH4','CN','CO','CO2','COOH','H','H2',...
    'H2O','H2O2','H2ObLb','H2Obcrb','HCCO','HCHO_formaldehy','HCN',...
    'HCO','HCOOH','HNC','HNCO','HNO','HO2','N','N2','N2O','NCO',...
    'NH','NH2','NH2OH','NH3','NO','NO2','O','O2','OCCN','OH','Si',...
    'Si2','Si2C','Si3','SiC','SiC2','SiH','SiH2','SiH3',...
    'SiH4','SiO','SiO2','Cbgrb','SiCbbb','SiO2ba_qzb','SiO2bb_qzb','SiO2bb_crtb'};
    display_species = {'H2', 'H', 'CH4', 'C2H2_acetylene', 'SiC2',...
            'Si', 'C', 'C2H', 'C3', 'CO', 'CO2', 'Cbgrb', 'SiCbbb',...
            'SiO2ba_qzb','SiO2bb_qzb','SiO2bb_crtb','H2O','H2ObLb','H2Obcrb'};
    tolN = 1e-18;
    % Load results CEA 
    results_CEA = data_CEA(filename, display_species);
    % Combustion Toolbox
    results_CT = run_CT('ProblemType', 'TP',...
                        'Temp', 200:10:5000,...
                        'Pressure', 1.01325,...
                        'Species', LS,...
                        'S_Fuel', Fuel,...
                        'N_Fuel', moles_Fuel,...
                        'S_Oxidizer', [],...
                        'phi', [],...
                        'tolN', tolN);
    problems_solved = length(results_CT.PD.range);
    % Display validation (plot)
    % * Molar fractions
    [~, fig1] = plot_molar_fractions(results_CT, results_CT.PS.strP, 'T', 'Xi', 'validation', results_CEA, 'display_species', display_species);
    % * Properties mixture 2
    fig2 = plot_properties_validation(results_CT, results_CEA, {'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T'}, {'rho', 'h', 'e', 'g', 'S', 'cP', 'cV', 'gamma_s', 'dVdp_T', 'dVdT_p'}, 'mix2');
    % Save plots
    folderpath = strcat(pwd,'\Validations\Figures\');
    stack_trace = dbstack;
    filename = stack_trace.name;
    saveas(fig1, strcat(folderpath, filename, '_molar'), 'svg');
    saveas(fig2, strcat(folderpath, filename, '_properties'), 'svg');
end