[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "combustion_toolbox"
authors = [{name = "Alberto Cuadra Lara", email = "acuadra@ing.uc3m.es"}]
dynamic = ["version", "description"]
readme = "README.md"


[project.license]
file = "LICENSE.md"