[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "combustion_toolbox"
version = "0.9.0"
readme = "README.md"

[[project.authors]]
name = "Alberto Cuadra Lara"
email = "acuadra@ing.uc3m.es"


[project.license]
file = "LICENSE.md"