function run_benchmarking()
    % Run benchmarking for selected validation tests.
    %
    % This function executes a series of validation tests to assess the
    % performance of the combustion toolbox.

    % Import packages
    import combustiontoolbox.utils.Benchmark

    % Define benchmark tests as function handles
    tests = getBenchmarkCases();

    % Create the Benchmark object with tests and number of iterations
    bench = Benchmark(tests, 'numIterations', 5);

    % Run the tests
    bench = bench.run();

    % Generate and display the report
    bench.report();
end

% SUB-PASS FUNCTIONS
function tests = getBenchmarkCases()
    % Define benchmark tests as function handles
    tests = {...
        @run_validation_TP_TEA_1,...
        @run_validation_TP_TEA_2,...
        @run_validation_TP_TEA_3,...
        @run_validation_TP_TEA_4,...
        @run_validation_TP_CEA_1,...
        @run_validation_TP_CEA_2,...
        @run_validation_TP_CEA_3,...
        @run_validation_TP_CEA_4,...
        @run_validation_TP_CEA_5,...
        @run_validation_TP_CEA_6,...
        @run_validation_TV_CEA_1,...
        @run_validation_TV_CEA_2,...
        @run_validation_HP_CEA_1,...
        @run_validation_HP_CEA_2,...
        @run_validation_HP_CEA_3,...
        @run_validation_HP_CEA_4,...
        @run_validation_EV_CEA_1,...
        @run_validation_SP_CEA_1,...
        @run_validation_SV_CEA_1,...
        @run_validation_SHOCK_IONIZATION_CEA_1,...
        @run_validation_SHOCK_IONIZATION_CEA_2,...
        @run_validation_SHOCK_R_IONIZATION_CEA_1,...
        @run_validation_SHOCK_R_IONIZATION_CEA_2,...
        @run_validation_SHOCK_POLAR_SDToolbox_1,...
        @run_validation_SHOCK_POLAR_SDToolbox_2,...
        @run_validation_SHOCK_PRANDTL_MEYER_SDToolbox_1, ...
        @run_validation_SHOCK_PRANDTL_MEYER_SDToolbox_2, ...
        @run_validation_DET_CEA_1,...
        @run_validation_DET_CEA_2,...
        @run_validation_DET_CEA_3,...
        @run_validation_DET_CEA_4,...
        @run_validation_DET_OVERDRIVEN_SDToolbox_1,...
        @run_validation_DET_POLAR_SDToolbox_1,...
        @run_validation_ROCKET_CEA_20,...
        @run_validation_ROCKET_CEA_21,...
        @run_validation_ROCKET_CEA_22,...
        @run_validation_ROCKET_CEA_23,...
        @run_validation_ROCKET_CEA_24,...
        @run_validation_ROCKET_CEA_25,...
    };

end